const ingredients=[
  {id:'sauce',name:'Tomato sauce',className:'sauce',color:'#d95e52'},
  {id:'cheese',name:'Cheese',className:'cheese',color:'#ffd76d'},
  {id:'pepperoni',name:'Pepperoni',className:'pepperoni',color:'#c9574c'},
  {id:'mushroom',name:'Mushrooms',className:'mushroom',color:'#bd8b66'},
  {id:'onion',name:'Onions',className:'onion',color:'#c58eb4'},
  {id:'pepper',name:'Bell peppers',className:'pepper',color:'#85a967'},
  {id:'sausage',name:'Sausage',className:'sausage',color:'#a85e45'},
  {id:'olive',name:'Olives',className:'olive',color:'#515c40'},
  {id:'basil',name:'Fresh basil',className:'basil',color:'#6c9562'}
];
const customers=['Mia','Leo','Ruby','Sam','Nora','Theo','Ava','Max'];
const orderSets=[['sauce','cheese'],['sauce','cheese','pepperoni'],['sauce','cheese','mushroom','onion'],['sauce','cheese','pepper','sausage'],['sauce','cheese','olive','basil'],['sauce','cheese','pepperoni','mushroom'],['sauce','cheese','mushroom','olive','basil']];
let order=[],selected=null,placed=[],money=0,score=0,day=1,busy=false;
const $=id=>document.getElementById(id); const item=id=>ingredients.find(x=>x.id===id);
function tray(x){return `<button class="ingredient" type="button" data-id="${x.id}" aria-label="Select ${x.name}"><span class="ingredient-graphic ${x.className}" aria-hidden="true"></span><span class="ingredient-name">${x.name}</span></button>`}
function renderTrays(){$('topTrays').innerHTML=ingredients.slice(0,6).map(tray).join('');$('sideTrays').innerHTML=ingredients.slice(6).map(tray).join('')}
function newOrder(){order=[...orderSets[Math.floor(Math.random()*orderSets.length)]]; $('customerName').textContent=customers[Math.floor(Math.random()*customers.length)]; $('orderTitle').textContent=order.length===2?'Classic cheese':order.length>4?'Market garden':'Custom favorite'; $('orderText').textContent=order.map(id=>item(id).name).join(', '); $('orderChips').innerHTML=order.map(id=>`<span class="order-chip" style="--chip:${item(id).color}" data-color="true"></span>`).join('')}
function message(text,good=false){$('message').textContent=text;$('message').style.background=good?'#ddf3e6':'#fff0d6';$('message').style.color=good?'#4f987f':'#986c4e'}
function selectIngredient(id,button){if(busy)return;if(id==='dough'){message('Your dough is already on the wooden peel.');return}selected=id;document.querySelectorAll('.ingredient').forEach(x=>x.classList.toggle('selected',x.dataset.id===id));$('placementHint').textContent=`${item(id).name} selected`;$('selectedDot').style.background=item(id).color;message(`Tap the pizza to place ${item(id).name.toLowerCase()}.`,true)}
function placeIngredient(event){if(!selected||busy){if(!selected)message('Choose an ingredient tray first, then tap the pizza.');return}const pizza=$('pizza'),rect=pizza.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width*100,y=(event.clientY-rect.top)/rect.height*100;if(Math.hypot(x-50,y-50)>43)return;const xItem=item(selected),top=document.createElement('span');top.className=`placed-topping ingredient-graphic ${xItem.className}`;top.style.left=`${x}%`;top.style.top=`${y}%`;top.setAttribute('aria-label',xItem.name);$('toppings').appendChild(top);placed.push(selected);$('placementHint').textContent=`${xItem.name} added`;selected=null;document.querySelectorAll('.ingredient').forEach(x=>x.classList.remove('selected'));message(`${xItem.name} added! Pick another topping.`,true)}
function clearPizza(){if(busy)return;placed=[];selected=null;$('toppings').innerHTML='';document.querySelectorAll('.ingredient').forEach(x=>x.classList.remove('selected'));$('placementHint').textContent='Choose an ingredient';$('selectedDot').style.background='#d9bfa3';message('Fresh dough, fresh start!')}
function bakePizza(){if(busy)return;if(!placed.length){message('Add some toppings before baking.');return}const unique=[...new Set(placed)],missing=order.filter(id=>!unique.includes(id)),extra=unique.filter(id=>!order.includes(id));busy=true;$('bakeBtn').disabled=true;$('clearBtn').disabled=true;$('pizza').classList.add('baking');message('Baking your pizza... listen for that sizzle!',true);setTimeout(()=>{busy=false;$('bakeBtn').disabled=false;$('clearBtn').disabled=false;$('pizza').classList.remove('baking');if(!missing.length&&!extra.length){const reward=10+order.length*2;money+=reward;score+=100;$('money').textContent=`$${money}`;$('score').textContent=score;day++;$('day').textContent=String(day).padStart(2,'0');message(`Perfect bake! You earned $${reward} and 100 points.`,true);clearPizza();newOrder()}else{const notes=[];if(missing.length)notes.push(`missing ${missing.map(id=>item(id).name).join(', ')}`);if(extra.length)notes.push(`too much ${extra.map(id=>item(id).name).join(', ')}`);message(`Almost there: ${notes.join(' and ')}.`)}},1100)}
renderTrays();newOrder();document.addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(button)selectIngredient(button.dataset.id,button)});$('pizza').addEventListener('click',placeIngredient);$('clearBtn').addEventListener('click',clearPizza);$('bakeBtn').addEventListener('click',bakePizza);$('pizza').addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();message('Tap or click the pizza to place your selected topping.')}});
